export const botImageGenerator = (): string[] => {
    const botUrl = [
        "https://robohash.org/nostrumrepellendustenetur.png?size=300x300&set=set1",
        "https://robohash.org/quidemconsequaturaut.png?size=300x300&set=set1",
        "https://robohash.org/idetcumque.png?size=300x300&set=set1",
        "https://robohash.org/nisinequequas.png?size=300x300&set=set1",
        "https://robohash.org/etutprovident.png?size=300x300&set=set1",
        "https://robohash.org/accusantiumetfacilis.png?size=300x300&set=set1",
        "https://robohash.org/blanditiisautlaudantium.png?size=300x300&set=set1",
        "https://robohash.org/quirationerem.png?size=300x300&set=set1",
        "https://robohash.org/aperiametfuga.png?size=300x300&set=set1",
        "https://robohash.org/similiquereprehenderitet.png?size=300x300&set=set1",
        "https://robohash.org/eiusautnihil.png?size=300x300&set=set1",
        "https://robohash.org/aliquamutvelit.png?size=300x300&set=set1",
        "https://robohash.org/autsaepeeveniet.png?size=300x300&set=set1",
        "https://robohash.org/consecteturveritatisid.png?size=300x300&set=set1",
        "https://robohash.org/temporibusexercitationemprovident.png?size=300x300&set=set1",
        "https://robohash.org/eiuslaborumaliquid.png?size=300x300&set=set1",
        "https://robohash.org/autearem.png?size=300x300&set=set1",
        "https://robohash.org/repellendusporrosint.png?size=300x300&set=set1",
        "https://robohash.org/ipsamexercitationemrem.png?size=300x300&set=set1",
        "https://robohash.org/adipisciconsequaturnostrum.png?size=300x300&set=set1",
        "https://robohash.org/iddolormaxime.png?size=300x300&set=set1",
        "https://robohash.org/verotemporecorrupti.png?size=300x300&set=set1",
        "https://robohash.org/ducimusquiaut.png?size=300x300&set=set1",
        "https://robohash.org/quisrationeerror.png?size=300x300&set=set1",
        "https://robohash.org/consequunturetquis.png?size=300x300&set=set1",
        "https://robohash.org/delenitipraesentiumaut.png?size=300x300&set=set1",
        "https://robohash.org/quidoloresit.png?size=300x300&set=set1",
        "https://robohash.org/beataequisaut.png?size=300x300&set=set1",
        "https://robohash.org/repellendusasperioresdolor.png?size=300x300&set=set1",
        "https://robohash.org/quodremnihil.png?size=300x300&set=set1",
        "https://robohash.org/isteoptiodolorem.png?size=300x300&set=set1",
        "https://robohash.org/vitaeutporro.png?size=300x300&set=set1",
        "https://robohash.org/oditdoloresullam.png?size=300x300&set=set1",
        "https://robohash.org/doloretqui.png?size=300x300&set=set1",
        "https://robohash.org/dolorumnumquamratione.png?size=300x300&set=set1",
        "https://robohash.org/sitvoluptatemipsa.png?size=300x300&set=set1",
        "https://robohash.org/essesaepeeaque.png?size=300x300&set=set1",
        "https://robohash.org/quinatuset.png?size=300x300&set=set1",
        "https://robohash.org/quivelitdolores.png?size=300x300&set=set1",
        "https://robohash.org/quascumqueaut.png?size=300x300&set=set1",
        "https://robohash.org/adrecusandaevoluptatem.png?size=300x300&set=set1",
        "https://robohash.org/facerenequevoluptas.png?size=300x300&set=set1",
        "https://robohash.org/quisuntest.png?size=300x300&set=set1",
        "https://robohash.org/laborumteneturquos.png?size=300x300&set=set1",
        "https://robohash.org/quosolutaprovident.png?size=300x300&set=set1",
        "https://robohash.org/eosrerumin.png?size=300x300&set=set1",
        "https://robohash.org/maioresofficiisrepellat.png?size=300x300&set=set1",
        "https://robohash.org/sedofficiadeserunt.png?size=300x300&set=set1",
        "https://robohash.org/necessitatibusquisunt.png?size=300x300&set=set1",
        "https://robohash.org/repellatdistinctioitaque.png?size=300x300&set=set1",
        "https://robohash.org/autnesciunteos.png?size=300x300&set=set1",
        "https://robohash.org/maximedelenitiveritatis.png?size=300x300&set=set1",
        "https://robohash.org/aliquidvoluptatemperspiciatis.png?size=300x300&set=set1",
        "https://robohash.org/temporibusavel.png?size=300x300&set=set1",
        "https://robohash.org/ututquasi.png?size=300x300&set=set1",
        "https://robohash.org/omnisidnumquam.png?size=300x300&set=set1",
        "https://robohash.org/ututquasi.png?size=300x300&set=set1",
        "https://robohash.org/fugasuntiure.png?size=300x300&set=set1",
        "https://robohash.org/voluptatemquasest.png?size=300x300&set=set1",
        "https://robohash.org/eumdelenitivoluptas.png?size=300x300&set=set1",
        "https://robohash.org/adeseruntnatus.png?size=300x300&set=set1",
        "https://robohash.org/dolormolestiascorrupti.png?size=300x300&set=set1",
        "https://robohash.org/etipsumsed.png?size=300x300&set=set1",
        "https://robohash.org/ametsitqui.png?size=300x300&set=set1",
        "https://robohash.org/exquisat.png?size=300x300&set=set1",
        "https://robohash.org/seddoloremest.png?size=300x300&set=set1",
        "https://robohash.org/aperiamautemconsectetur.png?size=300x300&set=set1",
        "https://robohash.org/nobisdoloremad.png?size=300x300&set=set1",
        "https://robohash.org/quibusdamveritatisquaerat.png?size=300x300&set=set1",
        "https://robohash.org/inearumrerum.png?size=300x300&set=set1",
        "https://robohash.org/inventoreisteut.png?size=300x300&set=set1",
        "https://robohash.org/velitfacerequo.png?size=300x300&set=set1",
        "https://robohash.org/delenitietqui.png?size=300x300&set=set1",
        "https://robohash.org/exeaut.png?size=300x300&set=set1",
        "https://robohash.org/eosquasiblanditiis.png?size=300x300&set=set1",
        "https://robohash.org/sedincidunteos.png?size=300x300&set=set1",
        "https://robohash.org/quoassumendadolorem.png?size=300x300&set=set1",
        "https://robohash.org/quiaesserepudiandae.png?size=300x300&set=set1",
        "https://robohash.org/quoassumendadolorem.png?size=300x300&set=set1",
        "https://robohash.org/invelitmaiores.png?size=300x300&set=set1",
        "https://robohash.org/architectocorruptiaccusantium.png?size=300x300&set=set1",
        "https://robohash.org/vitaeporrovoluptas.png?size=300x300&set=set1",
        "https://robohash.org/rationeducimusveritatis.png?size=300x300&set=set1",
        "https://robohash.org/consecteturinventoredolor.png?size=300x300&set=set1",
        "https://robohash.org/culpavoluptatemdeleniti.png?size=300x300&set=set1",
        "https://robohash.org/isteaeos.png?size=300x300&set=set1",
        "https://robohash.org/ipsumsedrecusandae.png?size=300x300&set=set1",
        "https://robohash.org/ipsumsedrecusandae.png?size=300x300&set=set1",
        "https://robohash.org/doloribusetsint.png?size=300x300&set=set1",
        "https://robohash.org/quiomniset.png?size=300x300&set=set1",
        "https://robohash.org/nobissimiliquequae.png?size=300x300&set=set1",
        "https://robohash.org/cumomnisautem.png?size=300x300&set=set1",
        "https://robohash.org/nullaconsequatursuscipit.png?size=300x300&set=set1",
        "https://robohash.org/eumdoloredoloribus.png?size=300x300&set=set1",
        "https://robohash.org/molestiaenihilautem.png?size=300x300&set=set1",
        "https://robohash.org/aliasquoest.png?size=300x300&set=set1",
        "https://robohash.org/nulladoloratque.png?size=300x300&set=set1",
        "https://robohash.org/commodiidasperiores.png?size=300x300&set=set1",
        "https://robohash.org/dictasolutanatus.png?size=300x300&set=set1",
        "https://robohash.org/sedhicquo.png?size=300x300&set=set1",
        "https://robohash.org/teneturquaereiciendis.png?size=300x300&set=set1",
    ]

    const getBotUrl = () => {
        for (let i = botUrl.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [botUrl[i], botUrl[j]] = [botUrl[j], botUrl[i]];
        }
        return botUrl
    }

    return getBotUrl()

}